### ISSUE TITLE
Gwt build error with latest elk master

### ISSUE THREAD

**Issue by jbeard4** [OpenKieler/elkjs#47]
Hi,

I wanted to let you know that the latest elk fails to compile with gwt. I think this might be a regression that was introduced in commit https://github.com/eclipse/elk/commit/8b194eda29d26362990c3de015cccd0fc3d56d41 yesterday. Here is the error:

```
root@ubuntu-s-16vcpu-64gb-nyc1-01:~/elkjs# npm run build

> elkjs@0.5.0 build /root/elkjs
> npm run gradle && npm run js


> elkjs@0.5.0 gradle /root/elkjs
> ./gradlew lib

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.5/userguide/gradle_daemon.html.
:copyElkJs UP-TO-DATE
:copyElk UP-TO-DATE
:copyEmul UP-TO-DATE
:generateXtextXtext UP-TO-DATE
:copyMelk UP-TO-DATE
:generateXtext SKIPPED
:compileJava UP-TO-DATE
:gwtcMinified
Compiling module org.eclipse.elk.js.ElkJs
   Ignored 27 units with compilation errors in first pass.
Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
   [ERROR] Errors in 'file:/root/elkjs/build/src/elk/org/eclipse/elk/alg/layered/p5edges/loops/labeling/SelfLoopLabelPositionEvaluator.java'
      [ERROR] Line 253: No source code is available for type java.awt.geom.Rectangle2D.Double; did you forget to inherit a required module?
   Tracing compile failure path for type 'org.eclipse.elk.alg.layered.p5edges.loops.labeling.SelfLoopLabelPositionEvaluator'
      [ERROR] Errors in 'file:/root/elkjs/build/src/elk/org/eclipse/elk/alg/layered/p5edges/loops/labeling/SelfLoopLabelPositionEvaluator.java'
         [ERROR] Line 253: No source code is available for type java.awt.geom.Rectangle2D.Double; did you forget to inherit a required module?
   [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible
:gwtcMinified FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gwtcMinified'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 21.564 secs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elkjs@0.5.0 gradle: `./gradlew lib`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elkjs@0.5.0 gradle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-15T13_25_49_351Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elkjs@0.5.0 build: `npm run gradle && npm run js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elkjs@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-15T13_25_49_372Z-debug.log
```

I can look into fixing this error, if that would be a useful contribution. Let me know what you think. Thanks.

**Comment by uruuru** [comment]
Yes, @le-cds can you please fix this? We have our own rect.

**Comment by jbeard4** [comment]
@uruuru @le-cds Do you have a guide for new contributors? Would you accept a PR fix?

**Comment by jbeard4** [comment]
I submitted a PR here: https://github.com/eclipse/elk/pull/364. Looking into submitting an ECL now. Thanks.

**Comment by uruuru** [comment]
By ECL you mean an Eclipse Contributor Agreement? 

Thanks for the PR. Principally it looks fine to me. I would've expected an `intersects` method in `ElkMath` or somewhere else in our code ... but I seem to be mistaken. Still, to be consistent, your method should be placed there. Could you also please add some documentation?

Also, @le-cds will have to take care of the PR (once you signed the ECA), for reasons.

**Comment by jbeard4** [comment]
Sorry, I meant ECA when I wrote ECL. I am having technical difficulties logging into the Eclipse Foundation, so this might take some time.

I will revise the PR per your notes. Thank you.

**Comment by jbeard4** [comment]
By the way, after the patch, I was able to build master successfully, and the new self-loop edge label positioning code is working pretty well!

<img width="878" alt="screen shot 2018-08-15 at 1 59 14 pm" src="https://user-images.githubusercontent.com/586962/44164806-05a3eb00-a095-11e8-963a-98802db0e71d.png">

**Comment by jbeard4** [comment]
@uruuru I made the changes you suggested and IP compliance checks pass. Please let me know if any further changes are needed. Thank you.

**Comment by le-cds** [comment]
> By the way, after the patch, I was able to build master successfully, and the new self-loop edge label positioning code is working pretty well!

I'm glad to hear that. Two weeks of my life well spent. :grinning:
